# Generated by Django 4.0.4 on 2022-05-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.AlterField(
            model_name='admin',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='charge',
            field=models.BigIntegerField(),
        ),
    ]
