# Generated by Django 4.0.4 on 2022-06-09 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_payment_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='cus_username',
        ),
    ]
