# Generated by Django 4.0.4 on 2022-06-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_username_customer_cus_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_name', models.TextField(max_length=20)),
                ('appointment_date', models.IntegerField()),
                ('appointment_time', models.IntegerField()),
                ('appointment_service', models.TextField()),
            ],
        ),
    ]
