# Generated by Django 4.0.4 on 2022-06-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
