# Generated by Django 4.0.4 on 2022-07-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('doctor', models.TextField()),
                ('detail', models.TextField()),
                ('treatment', models.TextField()),
                ('recommendation', models.TextField()),
            ],
        ),
    ]
