# Generated by Django 4.0.4 on 2022-07-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='address',
            field=models.CharField(blank=b'I01\n', max_length=100),
        ),
    ]
