# Generated by Django 4.0.4 on 2022-07-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_report_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='address',
            field=models.CharField(blank=b'I00\n', max_length=100),
        ),
    ]
