# Generated by Django 4.0.4 on 2022-08-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_report_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_feedback',
            field=models.TextField(null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AlterField(
            model_name='report',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
